[package]
name = "sifr_lowering"
version = "0.0.0"
publish = false
edition = { workspace = true }
rust-version = { workspace = true }
license = { workspace = true }

[dependencies]
sifr_diagnostics = { workspace = true }
sifr_ir = { workspace = true }
sifr_ipc = { workspace = true }
sifr_python_ast = { workspace = true }
sifr_python_parser = { workspace = true }
sifr_stdlib_imports = { workspace = true }
sifr_type_system = { workspace = true }
ruff_text_size = { workspace = true }
rust_decimal = "1.42.1"
bigdecimal = "0.4.10"
num-bigint = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
insta = { workspace = true }

[lints]
workspace = true
